const data = {
    "job_applications": [
      {
        "id": "cf455cec6105eaf9eea1903a73b375d8",
        "url": "/jobs/17257/applications/cf455cec6105eaf9eea1903a73b375d8",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-01-31T19:31:49.887Z",
        "hiring_organization": "LFi",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Ene 31",
        "sent_time_ago": "15 días",
        "edit_url": "/jobs/17257/applications/cf455cec6105eaf9eea1903a73b375d8/edit",
        "messages_url": "/jobs/17257/applications/cf455cec6105eaf9eea1903a73b375d8/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 17257,
          "title": "Desarrollador Angular",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "1400 - 1800",
          "user_id": 6957,
          "hiring_company": "",
          "hiring_organization": "LFi",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full",
            "flexible_hours",
            "informal_dresscode"
          ],
          "new": false,
          "show_salary": true,
          "min_salary": 1400,
          "max_salary": 1800,
          "seniority": "Junior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/6957/avatar-link.png",
          "url": "/empleos/programacion/desarrollador-full-stack-angular-lfi-remoto",
          "modality": "Full time",
          "published_at": "ene 26",
          "company": {
            "name": "LFi",
            "about": "Combinamos creatividad y tecnología al servicio de los negocios. ",
            "url": "/companies/lfi-cl"
          }
        }
      },
      {
        "id": "b1354ccea99774d19eeb502979371128",
        "url": "/jobs/22270/applications/b1354ccea99774d19eeb502979371128",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-01-31T18:54:31.023Z",
        "hiring_organization": "Leniolabs_",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Ene 31",
        "sent_time_ago": "15 días",
        "edit_url": "/jobs/22270/applications/b1354ccea99774d19eeb502979371128/edit",
        "messages_url": "/jobs/22270/applications/b1354ccea99774d19eeb502979371128/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 22270,
          "title": "Angular Developer",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": false,
          "salary": "3300 - 3500",
          "user_id": 4161,
          "hiring_company": "",
          "hiring_organization": "Leniolabs_",
          "remote_modality": "remote_local",
          "remote_zone": "Argentina; Chile; Colombia, Uruguay",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": true,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "health_coverage",
            "computer_provided",
            "informal_dresscode"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/4161/l-icon2.png",
          "url": "/empleos/programacion/full-stack-developer-leniolabs_-remote",
          "modality": "Full time",
          "published_at": "feb 06",
          "company": {
            "name": "Leniolabs_",
            "about": "Somos una empresa de desarrollo de software con sede en Argentina, Chile, España y USA.",
            "url": "/companies/leniolabs"
          }
        }
      },
      {
        "id": "6a26fb12fd9a3ecaddfa35257189fec9",
        "url": "/jobs/24901/applications/6a26fb12fd9a3ecaddfa35257189fec9",
        "youtube": null,
        "messages_count": 1,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": true,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-02-02T14:51:08.315Z",
        "hiring_organization": "FITCO",
        "last_messages_author": "TeamMember",
        "last_messages_date": "2022-02-03T21:33:45.967Z",
        "in_conversation": true,
        "hired": false,
        "sent_at_in_words": "Feb  2",
        "sent_time_ago": "13 días",
        "edit_url": "/jobs/24901/applications/6a26fb12fd9a3ecaddfa35257189fec9/edit",
        "messages_url": "/jobs/24901/applications/6a26fb12fd9a3ecaddfa35257189fec9/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 24901,
          "title": "Junior Software Developer Node.js Remoto",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "1800 - 2500",
          "user_id": 7813,
          "hiring_company": "",
          "hiring_organization": "FITCO",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Junior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/7813/Logo_verde_gradient.png",
          "url": "/empleos/programacion/junior-software-developer-node-js-remoto-fitco-remote",
          "modality": "Full time",
          "published_at": "ene 26",
          "company": {
            "name": "FITCO",
            "about": "Estamos transformando la industria fitness con tecnología\r\nBuscamos impactar en 100MM de personas",
            "url": "/companies/fitco"
          }
        }
      },
      {
        "id": "f3d3393e7e0d6525e731be397a13a6bc",
        "url": "/jobs/27344/applications/f3d3393e7e0d6525e731be397a13a6bc",
        "youtube": null,
        "messages_count": 0,
        "sent": false,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": true,
        "unread_messages_from_company": 0,
        "sent_at": null,
        "hiring_organization": "ScharfsteinLabs",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": null,
        "sent_time_ago": null,
        "edit_url": "/jobs/27344/applications/f3d3393e7e0d6525e731be397a13a6bc/edit",
        "messages_url": "/jobs/27344/applications/f3d3393e7e0d6525e731be397a13a6bc/messages",
        "send_url": "/jobs/27344/applications/f3d3393e7e0d6525e731be397a13a6bc/sendit",
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 27344,
          "title": "Desarrollador Front-end",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": true,
          "is_hot": false,
          "salary": "3800 - 5000",
          "user_id": 10336,
          "hiring_company": "",
          "hiring_organization": "ScharfsteinLabs",
          "remote_modality": "temporarily_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": false,
          "temporarily_remote": true,
          "remote_local": false,
          "city": "Santiago",
          "country": "Chile",
          "country_flag_url": "https://d2dgum4gsvdsrq.cloudfront.net/assets/flags/cl_mini-fabdc8612af2c25752582dd1d5694400e44800d698c064500f10cc059e29749a.png",
          "perks": [
            "remote_partial",
            "health_coverage",
            "computer_provided",
            "informal_dresscode",
            "beverages_and_snacks"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/10336/logo200_blanco.png",
          "url": "/empleos/programacion/desarrollador-frontend-scharfsteinlabs-santiago",
          "modality": "Full time",
          "published_at": "ene 25",
          "company": {
            "name": "ScharfsteinLabs",
            "about": "Scharfsteinlabs es la célula de innovación de Scharfstein, compañía líder en el mercado de tecnología de parking, seguridad y telecomunicaciones. ",
            "url": "/companies/scharfsteinlabs-cl"
          }
        }
      },
      {
        "id": "8764e6486f519b9622f9d847ae156312",
        "url": "/jobs/27388/applications/8764e6486f519b9622f9d847ae156312",
        "youtube": null,
        "messages_count": 1,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 1,
        "sent_at": "2022-01-31T18:46:16.578Z",
        "hiring_organization": "CLM Digital Solutions",
        "last_messages_author": "TeamMember",
        "last_messages_date": "2022-01-31T18:54:29.238Z",
        "in_conversation": true,
        "hired": false,
        "sent_at_in_words": "Ene 31",
        "sent_time_ago": "15 días",
        "edit_url": "/jobs/27388/applications/8764e6486f519b9622f9d847ae156312/edit",
        "messages_url": "/jobs/27388/applications/8764e6486f519b9622f9d847ae156312/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 27388,
          "title": "Desarrollador(a) Full-Stack",
          "description_headline": "¿Qué necesitas para ser nuestro próximo Desarrollador Full Stack?",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "3100 - 3200",
          "user_id": 8899,
          "hiring_company": "",
          "hiring_organization": "CLM Digital Solutions",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "wellness",
            "remote_full",
            "flexible_hours",
            "life_insurance",
            "digital_library",
            "health_coverage",
            "computer_provided",
            "informal_dresscode",
            "vacation_on_birthday"
          ],
          "new": true,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/8899/Logo_CLM_DS.PNG",
          "url": "/empleos/programacion/desarrollador-a-full-stack-clm-digital-solutions-remote-feea",
          "modality": "Full time",
          "published_at": "feb 14",
          "company": {
            "name": "CLM Digital Solutions",
            "about": "Somos un equipo de profesionales apasionados por la tecnología y nos encanta disfrutar de lo que hacemos.",
            "url": "/companies/clm-consultores"
          }
        }
      },
      {
        "id": "c44505576a64262c88c40b06f0ea1de6",
        "url": "/jobs/29124/applications/c44505576a64262c88c40b06f0ea1de6",
        "youtube": null,
        "messages_count": 0,
        "sent": false,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": true,
        "unread_messages_from_company": 0,
        "sent_at": null,
        "hiring_organization": "Reign",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": null,
        "sent_time_ago": null,
        "edit_url": "/jobs/29124/applications/c44505576a64262c88c40b06f0ea1de6/edit",
        "messages_url": "/jobs/29124/applications/c44505576a64262c88c40b06f0ea1de6/messages",
        "send_url": "/jobs/29124/applications/c44505576a64262c88c40b06f0ea1de6/sendit",
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 29124,
          "title": "Junior Web Developer",
          "description_headline": "Requirements",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "1900",
          "user_id": 2963,
          "hiring_company": "",
          "hiring_organization": "Reign",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "accessible",
            "remote_full",
            "flexible_hours",
            "internal_talks",
            "bicycle_parking",
            "computer_provided",
            "informal_dresscode",
            "vacation_over_legal",
            "beverages_and_snacks"
          ],
          "new": true,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Junior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/2963/Reign-logo-corona-bg-white.png",
          "url": "/empleos/programacion/junior-web-developer-reign-remote",
          "modality": "Full time",
          "published_at": "feb 14",
          "company": {
            "name": "Reign",
            "about": "Technology is our kingdom. At Reign, we deliver digital transformation by the ideation, design, and development of web and mobile applications. ",
            "url": "/companies/reign"
          }
        }
      },
      {
        "id": "cc59a509a1cbf23dc58c4e6ceff1686f",
        "url": "/jobs/29388/applications/cc59a509a1cbf23dc58c4e6ceff1686f",
        "youtube": null,
        "messages_count": 0,
        "sent": false,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": true,
        "unread_messages_from_company": 0,
        "sent_at": null,
        "hiring_organization": "Rankmi",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": null,
        "sent_time_ago": null,
        "edit_url": "/jobs/29388/applications/cc59a509a1cbf23dc58c4e6ceff1686f/edit",
        "messages_url": "/jobs/29388/applications/cc59a509a1cbf23dc58c4e6ceff1686f/messages",
        "send_url": "/jobs/29388/applications/cc59a509a1cbf23dc58c4e6ceff1686f/sendit",
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 29388,
          "title": "Front-end Engineer Semi Senior",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": false,
          "salary": "2700 - 2900",
          "user_id": 1339,
          "hiring_company": "",
          "hiring_organization": "Rankmi",
          "remote_modality": "remote_local",
          "remote_zone": "Chile, Perú, Colombia, Argentina, Uruguay, Paraguay, Guatemala, Bolivia",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": true,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "flexible_hours",
            "informal_dresscode",
            "vacation_over_legal"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/1339/WhatsApp_Image_2021-06-09_at_12.53.09.jpeg",
          "url": "/empleos/programacion/frontend-engineer-semi-senior-rankmi-remote",
          "modality": "Full time",
          "published_at": "ene 30",
          "company": {
            "name": "Rankmi",
            "about": "Rankmi es la plataforma para automatizar la gestión de personas líder en Latinoamérica. Nos encanta trabajar con personas innovadoras, creativas y que siempre estén desafiando los límites. ¡Revisa a continuación las oportunidades que tenemos para ti!",
            "url": "/companies/rankmi"
          }
        }
      },
      {
        "id": "d26ba2654ea024c32e652762c5cc43f3",
        "url": "/jobs/29868/applications/d26ba2654ea024c32e652762c5cc43f3",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-01-31T19:44:06.702Z",
        "hiring_organization": "Ki Teknology",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Ene 31",
        "sent_time_ago": "15 días",
        "edit_url": "/jobs/29868/applications/d26ba2654ea024c32e652762c5cc43f3/edit",
        "messages_url": "/jobs/29868/applications/d26ba2654ea024c32e652762c5cc43f3/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 29868,
          "title": "Desarrollador Node.js + Angular",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "2100 - 2300",
          "user_id": 2708,
          "hiring_company": "Ki Teknology",
          "hiring_organization": "Ki Teknology",
          "remote_modality": "remote_local",
          "remote_zone": "Latam",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": true,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "relocation",
            "flexible_hours",
            "health_coverage",
            "computer_provided",
            "informal_dresscode"
          ],
          "new": false,
          "show_salary": true,
          "min_salary": 2100,
          "max_salary": 2300,
          "seniority": "Junior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/2708/logo.png",
          "url": "/empleos/programacion/desarrolador-node-js-angular-nisum-chile-remote",
          "modality": "Full time",
          "published_at": "ene 24",
          "company": {
            "name": "Nisum Chile",
            "about": "Empresa de tecnologia y desarrollo de software con oficinas en USA, India y Chile.",
            "url": "/companies/nisum-technologies-f9b74a6d-f515-49db-9794-43dba0b56168"
          }
        }
      },
      {
        "id": "2d08c4b4e2ce14aac60fae1036311ab6",
        "url": "/jobs/29960/applications/2d08c4b4e2ce14aac60fae1036311ab6",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-01-31T19:28:22.584Z",
        "hiring_organization": "Geovictoria",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Ene 31",
        "sent_time_ago": "15 días",
        "edit_url": "/jobs/29960/applications/2d08c4b4e2ce14aac60fae1036311ab6/edit",
        "messages_url": "/jobs/29960/applications/2d08c4b4e2ce14aac60fae1036311ab6/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 29960,
          "title": "Desarrollador Full-Stack",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "2400 - 2500",
          "user_id": 6703,
          "hiring_company": "",
          "hiring_organization": "Geovictoria",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full",
            "pet_friendly",
            "flexible_hours",
            "bicycle_parking",
            "computer_provided",
            "informal_dresscode",
            "beverages_and_snacks"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Junior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/6703/logo_latinoamerica.png",
          "url": "/empleos/programacion/desarrollador-front-end-geovictoria-buenos-aires",
          "modality": "Full time",
          "published_at": "ene 29",
          "company": {
            "name": "Geovictoria",
            "about": "GeoVictoria es una empresa de Analitica de Fuerza Laboral enfocada completamente en la calidad de Servicio ",
            "url": "/companies/geovictoria"
          }
        }
      },
      {
        "id": "7821b9574b6eae5024480edb17417fce",
        "url": "/jobs/30344/applications/7821b9574b6eae5024480edb17417fce",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-02-09T19:06:44.357Z",
        "hiring_organization": "Barracks SpA",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Feb  9",
        "sent_time_ago": "6 días",
        "edit_url": "/jobs/30344/applications/7821b9574b6eae5024480edb17417fce/edit",
        "messages_url": "/jobs/30344/applications/7821b9574b6eae5024480edb17417fce/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 30344,
          "title": "Software Engineer",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": true,
          "is_hot": true,
          "salary": "2900",
          "user_id": 6968,
          "hiring_company": "",
          "hiring_organization": "Barracks SpA",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full",
            "flexible_hours",
            "life_insurance",
            "company_retreats",
            "dental_insurance",
            "computer_provided",
            "performance_bonus",
            "informal_dresscode",
            "vacation_on_birthday"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/6968/barracks_cuadrado_fondo_rojo.png",
          "url": "/empleos/programacion/software-engineer-barracks-spa-remote-1776",
          "modality": "Full time",
          "published_at": "ene 25",
          "company": {
            "name": "Barracks SpA",
            "about": "Buscamos la profesionalización de los E-Sports desde latino américa para el mundo.  Buscando siempre crecer, siempre con la necesidad de ser mejores personas, compañeros de equipo, jugadores, mejores gamers. ",
            "url": "/companies/barracks"
          }
        }
      },
      {
        "id": "dc2120136a316702e5f88a30cbf82a2f",
        "url": "/jobs/30518/applications/dc2120136a316702e5f88a30cbf82a2f",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-02-07T17:59:38.880Z",
        "hiring_organization": "ZerviZ",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Feb  7",
        "sent_time_ago": "8 días",
        "edit_url": "/jobs/30518/applications/dc2120136a316702e5f88a30cbf82a2f/edit",
        "messages_url": "/jobs/30518/applications/dc2120136a316702e5f88a30cbf82a2f/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 30518,
          "title": "Desarrollador Front-end",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": false,
          "salary": "2700 - 2800",
          "user_id": 6167,
          "hiring_company": "",
          "hiring_organization": "ZerviZ",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full",
            "flexible_hours",
            "health_coverage",
            "computer_provided",
            "informal_dresscode"
          ],
          "new": true,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/6167/logo_vector_transparente.png",
          "url": "/empleos/programacion/desarrollador-frontend-zerviz-remote",
          "modality": "Full time",
          "published_at": "feb 14",
          "company": {
            "name": "ZerviZ",
            "about": "Porque innovamos, implementamos y transformamos proyectos y procesos de transformación digital junto a la mejor tecnología ¡te estamos buscando! ⚡",
            "url": "/companies/zerviz"
          }
        }
      },
      {
        "id": "97aa54c32db853a46dbb4c7c7807e7fe",
        "url": "/jobs/30599/applications/97aa54c32db853a46dbb4c7c7807e7fe",
        "youtube": null,
        "messages_count": 0,
        "sent": false,
        "read": false,
        "deleted": false,
        "closure": false,
        "wip_application": true,
        "unread_messages_from_company": 0,
        "sent_at": null,
        "hiring_organization": "Defontana",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": null,
        "sent_time_ago": null,
        "edit_url": "/jobs/30599/applications/97aa54c32db853a46dbb4c7c7807e7fe/edit",
        "messages_url": "/jobs/30599/applications/97aa54c32db853a46dbb4c7c7807e7fe/messages",
        "send_url": "/jobs/30599/applications/97aa54c32db853a46dbb4c7c7807e7fe/sendit",
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 30599,
          "title": "Desarrollador Net Core",
          "description_headline": "Qualifications and requirements",
          "recommended": false,
          "pinned": false,
          "is_hot": false,
          "salary": "900 - 1200",
          "user_id": 7648,
          "hiring_company": "",
          "hiring_organization": "Defontana",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full"
          ],
          "new": false,
          "show_salary": true,
          "min_salary": 900,
          "max_salary": 1200,
          "seniority": "Sin experiencia",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/7648/logodefontana200x200.jpg",
          "url": "/empleos/programacion/desarrollador-net-core-defontana-remote-3548",
          "modality": "Full time",
          "published_at": "feb 04",
          "company": {
            "name": "Defontana",
            "about": "Defontana, empresa líder en soluciones empresariales 100% web para pequeñas y medianas empresas.",
            "url": "/companies/defontana-cl-3498"
          }
        }
      },
      {
        "id": "bd049774bd00409f162380188db2e97e",
        "url": "/jobs/30669/applications/bd049774bd00409f162380188db2e97e",
        "youtube": null,
        "messages_count": 0,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-02-08T06:10:52.213Z",
        "hiring_organization": "42labs",
        "last_messages_author": null,
        "last_messages_date": null,
        "in_conversation": false,
        "hired": false,
        "sent_at_in_words": "Feb  8",
        "sent_time_ago": "7 días",
        "edit_url": "/jobs/30669/applications/bd049774bd00409f162380188db2e97e/edit",
        "messages_url": "/jobs/30669/applications/bd049774bd00409f162380188db2e97e/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 30669,
          "title": "Full-Stack Angular/Spring Boot",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": false,
          "salary": "2700",
          "user_id": 8196,
          "hiring_company": "",
          "hiring_organization": "42labs",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full",
            "life_insurance",
            "computer_repairs",
            "dental_insurance",
            "computer_provided",
            "informal_dresscode",
            "vacation_on_birthday"
          ],
          "new": false,
          "show_salary": false,
          "min_salary": null,
          "max_salary": null,
          "seniority": "Semi Senior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/8196/Captura_de_Pantalla_2020-02-04_a_la_s__17.18.07.png",
          "url": "/empleos/programacion/fullstack-angular-springboot-42labs-santiago",
          "modality": "Full time",
          "published_at": "feb 07",
          "company": {
            "name": "42labs",
            "about": "Se necesita creatividad a la hora de aplicar la innovación tecnológica al servicio de la solución de tus problemas, en 42Labs puedes contar con ello.",
            "url": "/companies/42labs"
          }
        }
      },
      {
        "id": "e18b7dbbe6c3ff11262059b1ace4a755",
        "url": "/jobs/30744/applications/e18b7dbbe6c3ff11262059b1ace4a755",
        "youtube": null,
        "messages_count": 8,
        "sent": true,
        "read": true,
        "deleted": false,
        "closure": false,
        "wip_application": false,
        "unread_messages_from_company": 0,
        "sent_at": "2022-02-09T19:13:29.367Z",
        "hiring_organization": "Selaski",
        "last_messages_author": "TeamMember",
        "last_messages_date": "2022-02-14T20:48:08.365Z",
        "in_conversation": true,
        "hired": true,
        "sent_at_in_words": "Feb  9",
        "sent_time_ago": "6 días",
        "edit_url": "/jobs/30744/applications/e18b7dbbe6c3ff11262059b1ace4a755/edit",
        "messages_url": "/jobs/30744/applications/e18b7dbbe6c3ff11262059b1ace4a755/messages",
        "send_url": null,
        "no_news_from_company_since": 0,
        "webpro": {
          "id": "07308c5cbf170f42d391af54461dc4e3"
        },
        "job": {
          "id": 30744,
          "title": "Full-Stack (Angular Node.js)",
          "description_headline": "Requerimientos del cargo",
          "recommended": false,
          "pinned": false,
          "is_hot": true,
          "salary": "1500",
          "user_id": 11212,
          "hiring_company": "",
          "hiring_organization": "Selaski",
          "remote_modality": "fully_remote",
          "remote_zone": "",
          "hidden": false,
          "remote": true,
          "temporarily_remote": false,
          "remote_local": false,
          "city": null,
          "country": {
            "AE": "Emiratos Árabes Unidos",
            "AF": "Afganistán",
            "AR": "Argentina",
            "AU": "Australia",
            "BE": "Bélgica",
            "BO": "Bolivia",
            "BR": "Brasil",
            "CA": "Canadá",
            "CH": "Suiza",
            "CL": "Chile",
            "CR": "Costa Rica",
            "CN": "China",
            "CU": "Cuba",
            "CO": "Colombia",
            "CZ": "República Checa",
            "DE": "Alemania",
            "DK": "Dinamarca",
            "DO": "República Dominicana",
            "DZ": "Argelia",
            "EC": "Ecuador",
            "EE": "Estonia",
            "ES": "España",
            "FI": "Finlandia",
            "FR": "Francia",
            "GB": "Reino Unido",
            "GR": "Grecia",
            "GT": "Guatemala",
            "HK": "Hong Kong",
            "HN": "Honduras",
            "HR": "Croacia",
            "HT": "Haití",
            "ID": "Indonesia",
            "IE": "Irlanda",
            "IL": "Israel",
            "IN": "India",
            "IR": "Irán",
            "IT": "Italia",
            "JP": "Japón",
            "KE": "Kenia",
            "KH": "Camboya",
            "KR": "República de Corea",
            "LV": "Letonia",
            "MT": "Malta",
            "MX": "México",
            "MY": "Malasia",
            "NG": "Nigeria",
            "NI": "Nicaragua",
            "NL": "Países Bajos",
            "false": "Noruega",
            "NZ": "Nueva Zelanda",
            "PA": "Panamá",
            "PE": "Perú",
            "PH": "Filipinas",
            "PK": "Pakistán",
            "PR": "Puerto Rico",
            "PT": "Portugal",
            "PL": "Polonia",
            "PY": "Paraguay",
            "QA": "Catar",
            "RE": "Remoto",
            "RO": "Rumania",
            "RS": "Serbia",
            "RU": "Rusia",
            "SA": "Arabia Saudita",
            "SE": "Suecia",
            "SV": "El Salvador",
            "TH": "Tailandia",
            "TN": "Túnez",
            "TT": "Trinidad y Tobago",
            "TW": "República de China (Taiwan)",
            "UA": "Ucrania",
            "US": "Estados Unidos",
            "UY": "Uruguay",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "VU": "Vanuatu",
            "ZA": "Sudáfrica"
          },
          "country_flag_url": null,
          "perks": [
            "remote_full",
            "equity_offered",
            "flexible_hours",
            "informal_dresscode"
          ],
          "new": false,
          "show_salary": true,
          "min_salary": 1500,
          "max_salary": 1500,
          "seniority": "Junior",
          "logo_url": "https://getonbrd-prod.s3.amazonaws.com/uploads/users/logo/11212/Logo_Disminuido.png",
          "url": "/empleos/programacion/full-stack-angular-selaski-santiago",
          "modality": "Full time",
          "published_at": "feb 09",
          "company": {
            "name": "Selaski",
            "about": "Software de gestión de comercio internacional",
            "url": "/companies/selaski"
          }
        }
      }
    ]
};

const dataTabla = [
    {
        titulo: "titulo",
        modalidad: "full time",
        empresa: "abv",
        ciudad: "peru"

    },
    {
        titulo: "titulo2",
        modalidad: "full time2",
        empresa: "abv2",
        ciudad: "peru2"

    },
]

function loadJobs(){
    const tbody = document.getElementById("tbody");
    let div = "";
    const arrayEntrada = data.job_applications;

    for (let index = 0; index < arrayEntrada.length; index++) {
        const element = arrayEntrada[index];

     
        
        div+=
        `<tr>
        <td> ${element.job.title} </td> 
        <td> ${element.job.company.name} </td>`;

        if (element.job.remote) {

            const array = element.job.perks;
     
            div+= `<td> remoto `;
            for (let index = 0; index < array.length; index++) {
                const element = array[index];
                if (element == "remote_full") {
                    div+= `<i class="fa fa-globe" aria-hidden="true"></i>`;
                }
                if (element == "flexible_hours") {
                    div+= `<i class="fa fa-clock-o" aria-hidden="true"></i>`;
                }
                if (element == "informal_dresscode") {
                    div+= `<i class="fa fa-flag" aria-hidden="true"></i>`;
                }
                if (element == "vacation_over_legal") {
                    div+= `<i class="fa fa-tree" aria-hidden="true"></i>`;
                }
                if (element == "internal_talks") {
                    div+= `<i class="fa fa-phone" aria-hidden="true"></i>`;
                }
                if (element == "bicycle_parking") {
                    div+= `<i class="fa fa-bicycle" aria-hidden="true"></i>`;
                }
                if (element == "computer_provided") {
                    div+= `<i class="fa fa-desktop" aria-hidden="true"></i>`;
                }
                if (element == "beverages_and_snacks") {
                    div+= `<i class="fa fa-apple" aria-hidden="true"></i>`;
                }
                if (element == "accessible") {
                    div+= `<i class="fa fa-wheelchair-alt" aria-hidden="true"></i>`;
                }
                
            }
            
         

        }else{
            div+= `<td> ${ element.job.city} </td>`;
            
        }

        if (element.job.show_salary) {
            div+=  `<td> ${element.job.salary}  </td>`
        }else{
            div+=  `<td>  </td>`
        }
    

        if (element.messages_count && element.unread_messages_from_company) {
            div+= `<td> <i class="fa fa-comments" aria-hidden="true"></i>  ${element.messages_count} <i class="fa fa-circle" aria-hidden="true"></i> </td>`     
        }else{
            div+= `<td> <i class="fa fa-comments" aria-hidden="true"></i> 0 </td>`;
        }
            





        if (!element.sent) {
            div+=` <td>  Por enviar </td>`;
        }

        if (element.sent && !element.read) {
            div+=` <td>  Enviado </td>`;
        }
        if (element.sent && element.read && !element.hired && !element.closure) {
            div+=` <td>  Enviado <i class="fa fa-eye" aria-hidden="true"></i></td>`;
        }
        if (element.hired ) {
            div+=` <td>  Contratado </td>`;
        }
        if (!element.hired && element.closure) {
            div+=` <td>  Proceso Finalizado </td>`;
        }
        


        
      


        if (element.sent ) {
            div +=
            `<td> Enviada hace ${element.sent_time_ago}  </td>
             </tr>`;
        }else{
            div +=
            `<td> </td>
            </tr>`;
        }
        
    }
    tbody.innerHTML = div;
}
